### PR TITLE
FAILING: Add failing test MWE for prefixes not available for posts

### LINKED ISSUE #256: Prefixes can not be found in posts
MWE #257

### PR DESCRIPTION
**Pull request by white-gecko**
Fix #256 

- [x] Create a new branch for the fix
- [x] fix it to work also for posts using a gem based theme
- [x] check what is about documents

### CODE REVIEW

**Comment by white-gecko** [comment]
Why is the `instance_template_mapping` important? I've defined the layout for the post already in its front matter.
Also is the path calculation really as stable as `page.instance_variable_get(:@base)`? E.g. if I execute jekyll from within a different directory?

**Comment by Simaris** [comment]
your restriction lets jekyll-rdf render a resource.
This resource needs a template.  The rendering of the post and the rendering of a resource are two different things.
They just might get merged in the end.

**Comment by white-gecko** [comment]
Ok I understand this part.
What do you think about the path?

**Comment by Simaris** [comment]
the path part should be stable, but we should test this by loading posts from a theme (if that is even possible).
Then we know for certain.

**Comment by white-gecko** [comment]
I've tested it with the jod theme and it does not work. The system does not find the prefix file because it is looking for it in the local directory and not in the jekyll base path.

**Comment by Simaris** [comment]
turns out document hooks are always called for each kind of documents (page, posts).
I don't think we should implement a prefix hook for all documents, since we can only be sure about specifics if the document is a page or post.

**Pull request closed without merging**
