### PR TITLE
Support for Construct Query

### LINKED ISSUE #246: Support Construct Queries
we should support things like this:

```liquid
{% assign query = 'construct where {?resourceUri ?p ?o}' %}
{{ page.rdf | sparql_query: query }}
```

In this way we could embed the rdf data in a file.

### PR DESCRIPTION
**Pull request by Simaris**
Fix #246
- [x] inject data through constructs
- [x] tests
- [x] make data changes local to page?

### CODE REVIEW

**Comment by white-gecko** [comment]
Please integrate this into the `sparql_query` filter.

**Comment by white-gecko** [comment]
How do I serialize a graph to turtle or jsonld?

**Comment by Simaris** [comment]
currently, you can use `{{graph_variable}}'. There are also `graph_variable.to_nquads' (which is the same as before) and `graph_variable.to_ntriples', but liquid does not seem to print their results.

**Comment by white-gecko** [comment]
The result of the construct query needs to be kept separate from the original graph.

**Pull request merged**
